-- =====================================================================
-- Finance: money locations, suppliers, categories, agreements,
-- and a single money_movements table for every money in / out / transfer.
--
-- Assumes the legacy `transactions` table has already been dropped.
-- `invoice_disbursements` is NOT dropped here: switch the invoice pages
-- to money_movements first, then drop it in a follow-up migration.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Money locations: where money physically sits
--    Nextudio's own places (bank, safe, Whish...) have no project.
--    Each project has exactly one site fund.
-- ---------------------------------------------------------------------
create table money_locations (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  kind        text        not null check (kind in ('bank', 'cash', 'wallet', 'site_fund')),
  currency    text        not null default 'USD',
  project_id  bigint      references projects(id) on delete restrict,
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),

  -- a site fund always belongs to a project; Nextudio's own places never do
  constraint site_fund_has_project check (
    (kind = 'site_fund' and project_id is not null)
    or (kind <> 'site_fund' and project_id is null)
  )
);

-- one site fund per project
create unique index money_locations_one_site_fund_per_project
  on money_locations (project_id) where kind = 'site_fund';


-- ---------------------------------------------------------------------
-- 2. Suppliers and site workers (people who are not clients or employees)
-- ---------------------------------------------------------------------
create table suppliers (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  phone       text,
  trade       text,                 -- e.g. 'Steel', 'Concrete', 'Masonry'
  notes       text,
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now()
);

-- stops "Mamdouh" and "mamdouh " from becoming two people
create unique index suppliers_unique_name on suppliers (lower(trim(name)));


-- ---------------------------------------------------------------------
-- 3. Categories: what the money was for, in plain words
-- ---------------------------------------------------------------------
create table categories (
  id          bigint generated by default as identity primary key,
  name        text        not null unique,
  direction   text        not null check (direction in ('in', 'out')),
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now()
);

-- starter list, based on the categories used in Polypuss
insert into categories (name, direction) values
  ('Professional fees',       'in'),
  ('Client funds',            'in'),
  ('Concrete works',          'out'),
  ('Ready-mix',               'out'),
  ('Steel supply',            'out'),
  ('Excavation',              'out'),
  ('Masonry works',           'out'),
  ('Tiling works',            'out'),
  ('Plaster works',           'out'),
  ('Painting works',          'out'),
  ('Cladding works',          'out'),
  ('Waterproofing materials', 'out'),
  ('Electrical works',        'out'),
  ('Mechanical works',        'out'),
  ('Plumbing works',          'out'),
  ('Miscellaneous supplies',  'out'),
  ('Engineering fees',        'out'),
  ('Permits & licenses',      'out'),
  ('Salaries',                'out'),
  ('Site labor',              'out'),
  ('Rent',                    'out'),
  ('Internet & software',     'out'),
  ('Office expenses',         'out'),
  ('Bank commissions',        'out'),
  ('Tips & donations',        'out');


-- ---------------------------------------------------------------------
-- 4. Agreements: what was agreed with a supplier on a project
--    (lets the system show paid so far vs. still owed)
-- ---------------------------------------------------------------------
create table supplier_agreements (
  id             bigint generated by default as identity primary key,
  project_id     bigint        not null references projects(id)  on delete restrict,
  supplier_id    bigint        not null references suppliers(id) on delete restrict,
  agreed_amount  numeric(14,2) not null check (agreed_amount > 0),
  description    text,
  created_at     timestamptz   not null default now()
);


-- ---------------------------------------------------------------------
-- 5. Default Nextudio share per project (pre-fills the split on income)
-- ---------------------------------------------------------------------
alter table projects
  add column nextudio_share_percent numeric(5,2) not null default 0
  check (nextudio_share_percent between 0 and 100);


-- ---------------------------------------------------------------------
-- 6. Money movements: every money in, money out, and transfer
--
--    type = 'in'       -> location_id is where the money arrived
--    type = 'out'      -> location_id is where the money left from
--    type = 'transfer' -> location_id is the source, to_location_id the destination
-- ---------------------------------------------------------------------
create table money_movements (
  id                  bigint generated by default as identity primary key,
  movement_date       date          not null,
  type                text          not null check (type in ('in', 'out', 'transfer')),
  amount              numeric(14,2) not null check (amount > 0),

  location_id         bigint        not null references money_locations(id) on delete restrict,
  to_location_id      bigint                 references money_locations(id) on delete restrict,

  project_id          bigint        references projects(id)    on delete restrict,
  client_id           bigint        references clients(id)     on delete restrict,
  employee_id         bigint        references employees(id)   on delete restrict,
  supplier_id         bigint        references suppliers(id)   on delete restrict,
  category_id         bigint        references categories(id)  on delete restrict,

  invoice_id          bigint        references invoices(id)    on delete restrict,
  payment_id          bigint        references payments(id)    on delete restrict,
  group_id            uuid,         -- links the parts of one split client payment

  note                text,
  reference           text,         -- receipt number, check number, etc.
  created_by_user_id  bigint        references app_users(id)   on delete set null,
  created_at          timestamptz   not null default now(),
  updated_at          timestamptz   not null default now(),

  -- transfers need a different destination; other types have none
  constraint transfer_has_destination check (
    (type = 'transfer' and to_location_id is not null and to_location_id <> location_id)
    or (type <> 'transfer' and to_location_id is null)
  ),

  -- a movement involves at most one person
  constraint one_person_only check (
    num_nonnulls(client_id, employee_id, supplier_id) <= 1
  )
);

create index money_movements_date_idx     on money_movements (movement_date);
create index money_movements_project_idx  on money_movements (project_id);
create index money_movements_location_idx on money_movements (location_id);
create index money_movements_to_loc_idx   on money_movements (to_location_id);
create index money_movements_supplier_idx on money_movements (supplier_id);
create index money_movements_invoice_idx  on money_movements (invoice_id);
create index money_movements_payment_idx  on money_movements (payment_id);
create index money_movements_group_idx    on money_movements (group_id);


-- ---------------------------------------------------------------------
-- 7. Audit trail, same idea as payment_revisions:
--    snapshot the old row before every correction
-- ---------------------------------------------------------------------
create table money_movement_revisions (
  id                  bigint generated by default as identity primary key,
  money_movement_id   bigint      not null references money_movements(id) on delete cascade,
  changed_by_user_id  bigint      references app_users(id) on delete set null,
  changed_at          timestamptz not null default now(),
  previous            jsonb       not null
);


-- ---------------------------------------------------------------------
-- 8. Every project gets a site fund automatically
-- ---------------------------------------------------------------------
create function create_site_fund_for_project() returns trigger
language plpgsql as $$
begin
  insert into money_locations (name, kind, project_id)
  values (new.name || ' - Site fund', 'site_fund', new.id);
  return new;
end;
$$;

create trigger projects_create_site_fund
  after insert on projects
  for each row execute function create_site_fund_for_project();

-- site funds for projects that already exist
insert into money_locations (name, kind, project_id)
select p.name || ' - Site fund', 'site_fund', p.id
from projects p
where not exists (
  select 1 from money_locations l
  where l.project_id = p.id and l.kind = 'site_fund'
);


-- ---------------------------------------------------------------------
-- 9. Report views (the frontend reads these like normal tables)
-- ---------------------------------------------------------------------

-- How much is in each place right now
create view location_balances as
select
  l.id,
  l.name,
  l.kind,
  l.currency,
  l.project_id,
  coalesce(sum(
    case
      when m.type = 'in'       and m.location_id    = l.id then  m.amount
      when m.type = 'out'      and m.location_id    = l.id then -m.amount
      when m.type = 'transfer' and m.location_id    = l.id then -m.amount
      when m.type = 'transfer' and m.to_location_id = l.id then  m.amount
    end
  ), 0) as balance
from money_locations l
left join money_movements m
  on m.location_id = l.id or m.to_location_id = l.id
where l.is_active
group by l.id;

-- Money in / out per project per month (transfers are not counted)
create view project_monthly_summary as
select
  m.project_id,
  date_trunc('month', m.movement_date)::date as month,
  sum(case when m.type = 'in'  then m.amount else 0 end) as money_in,
  sum(case when m.type = 'out' then m.amount else 0 end) as money_out
from money_movements m
where m.project_id is not null
  and m.type in ('in', 'out')
group by m.project_id, date_trunc('month', m.movement_date);

-- Per supplier per project: agreed vs. paid so far vs. still owed
create view supplier_project_totals as
with paid as (
  select project_id, supplier_id, sum(amount) as total_paid
  from money_movements
  where type = 'out' and supplier_id is not null and project_id is not null
  group by project_id, supplier_id
),
agreed as (
  select project_id, supplier_id, sum(agreed_amount) as total_agreed
  from supplier_agreements
  group by project_id, supplier_id
)
select
  coalesce(p.project_id, a.project_id)   as project_id,
  coalesce(p.supplier_id, a.supplier_id) as supplier_id,
  coalesce(a.total_agreed, 0)            as total_agreed,
  coalesce(p.total_paid, 0)              as total_paid,
  coalesce(a.total_agreed, 0) - coalesce(p.total_paid, 0) as remaining
from paid p
full outer join agreed a
  on a.project_id = p.project_id and a.supplier_id = p.supplier_id;
