-- =====================================================================
-- Multi-tenant, migration 3: project teams with roles, types of work,
-- and "same company" protections.
--
-- Still the "expand" phase: project_assignments stays in place and the
-- live app keeps using it. project_members is filled from it once, here;
-- the backend switch moves the app over to project_members.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Make "organization + id" a unique pair on the parent tables.
--    This is what allows a child row to say "my parent must belong to
--    MY company" (the protections in step 5).
-- ---------------------------------------------------------------------
alter table clients              add constraint clients_org_id_key              unique (organization_id, id);
alter table projects             add constraint projects_org_id_key             unique (organization_id, id);
alter table money_locations      add constraint money_locations_org_id_key      unique (organization_id, id);
alter table suppliers            add constraint suppliers_org_id_key            unique (organization_id, id);
alter table categories           add constraint categories_org_id_key           unique (organization_id, id);
alter table organization_members add constraint organization_members_org_id_key unique (organization_id, id);


-- ---------------------------------------------------------------------
-- 2. Project roles: each company's own list
-- ---------------------------------------------------------------------
create table project_roles (
  id               bigint generated by default as identity primary key,
  organization_id  bigint      not null default default_organization_id()
                   references organizations(id) on delete restrict,
  name             text        not null,
  created_at       timestamptz not null default now(),
  constraint project_roles_org_name_key unique (organization_id, name),
  constraint project_roles_org_id_key   unique (organization_id, id)
);

insert into project_roles (name) values
  ('Project lead'),
  ('Site architect'),
  ('Office architect');


-- ---------------------------------------------------------------------
-- 3. Project members: who works on which project, and as what.
--    One row per person per role (Omar can be both Project lead and
--    Site architect on the same project: two rows).
--    The three composite keys guarantee the project, the person and the
--    role all belong to the same company.
-- ---------------------------------------------------------------------
create table project_members (
  id                      bigint generated by default as identity primary key,
  organization_id         bigint      not null default default_organization_id()
                          references organizations(id) on delete restrict,
  project_id              bigint      not null,
  organization_member_id  bigint      not null,
  project_role_id         bigint      not null,
  is_active               boolean     not null default true,
  created_at              timestamptz not null default now(),

  constraint project_members_unique unique (project_id, organization_member_id, project_role_id),
  constraint project_members_project_fk foreign key (organization_id, project_id)
    references projects (organization_id, id) on delete restrict,
  constraint project_members_member_fk foreign key (organization_id, organization_member_id)
    references organization_members (organization_id, id) on delete restrict,
  constraint project_members_role_fk foreign key (organization_id, project_role_id)
    references project_roles (organization_id, id) on delete restrict
);

create index project_members_project_idx on project_members (project_id);
create index project_members_member_idx  on project_members (organization_member_id);

-- Copy today's assignments. Only the architects are assigned today,
-- so everyone starts as "Office architect"; roles can be changed later.
insert into project_members (organization_id, project_id, organization_member_id, project_role_id, is_active)
select p.organization_id, pa.project_id, e.organization_member_id, r.id, pa.is_active
from project_assignments pa
join projects p      on p.id = pa.project_id
join employees e     on e.id = pa.employee_id
join project_roles r on r.organization_id = p.organization_id and r.name = 'Office architect'
where e.organization_member_id is not null;


-- ---------------------------------------------------------------------
-- 4. Types of work: each company's list, and which apply to each project
-- ---------------------------------------------------------------------
create table service_types (
  id               bigint generated by default as identity primary key,
  organization_id  bigint      not null default default_organization_id()
                   references organizations(id) on delete restrict,
  name             text        not null,
  created_at       timestamptz not null default now(),
  constraint service_types_org_name_key unique (organization_id, name),
  constraint service_types_org_id_key   unique (organization_id, id)
);

insert into service_types (name) values
  ('Interior design'),
  ('Exterior design'),
  ('Supervision'),
  ('Contracting');

-- A linking table: the pair (project, type of work) identifies each row
create table project_service_types (
  organization_id  bigint not null default default_organization_id()
                   references organizations(id) on delete restrict,
  project_id       bigint not null,
  service_type_id  bigint not null,
  primary key (project_id, service_type_id),
  constraint project_service_types_project_fk foreign key (organization_id, project_id)
    references projects (organization_id, id) on delete restrict,
  constraint project_service_types_type_fk foreign key (organization_id, service_type_id)
    references service_types (organization_id, id) on delete restrict
);


-- ---------------------------------------------------------------------
-- 5. Same-company protections on the most important existing links.
--    Example: a project can only point to a client of its own company.
--    (Links that may be empty, like an estimate without a client, are
--    only checked when they are filled in.)
-- ---------------------------------------------------------------------
alter table projects add constraint projects_client_same_org
  foreign key (organization_id, client_id) references clients (organization_id, id);

alter table estimates add constraint estimates_client_same_org
  foreign key (organization_id, client_id) references clients (organization_id, id);
alter table estimates add constraint estimates_project_same_org
  foreign key (organization_id, project_id) references projects (organization_id, id);

alter table invoices add constraint invoices_client_same_org
  foreign key (organization_id, client_id) references clients (organization_id, id);
alter table invoices add constraint invoices_project_same_org
  foreign key (organization_id, project_id) references projects (organization_id, id);

alter table payments add constraint payments_project_same_org
  foreign key (organization_id, project_id) references projects (organization_id, id);

alter table money_locations add constraint money_locations_project_same_org
  foreign key (organization_id, project_id) references projects (organization_id, id);

alter table money_movements add constraint money_movements_location_same_org
  foreign key (organization_id, location_id) references money_locations (organization_id, id);
alter table money_movements add constraint money_movements_to_location_same_org
  foreign key (organization_id, to_location_id) references money_locations (organization_id, id);
alter table money_movements add constraint money_movements_project_same_org
  foreign key (organization_id, project_id) references projects (organization_id, id);
alter table money_movements add constraint money_movements_supplier_same_org
  foreign key (organization_id, supplier_id) references suppliers (organization_id, id);
alter table money_movements add constraint money_movements_category_same_org
  foreign key (organization_id, category_id) references categories (organization_id, id);
