-- =====================================================================
-- Multi-tenant, migration 1: organizations and their members.
--
-- "Expand" phase only: this adds new tables next to the old columns.
-- app_users.role and app_users.employee_id are NOT touched, so the live
-- app keeps working exactly as before. They are removed in a later
-- migration, once the backend reads roles from organization_members.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Organizations: one row per company using the system
-- ---------------------------------------------------------------------
create table organizations (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  created_at  timestamptz not null default now()
);

insert into organizations (name) values ('Nextudio');


-- ---------------------------------------------------------------------
-- 2. Organization members: the "work badges"
--    One row per person per company, with their role in that company.
--    The same user can have badges in several companies.
-- ---------------------------------------------------------------------
create table organization_members (
  id               bigint generated by default as identity primary key,
  organization_id  bigint      not null references organizations(id) on delete restrict,
  user_id          bigint      not null references app_users(id)     on delete restrict,
  role             text        not null check (role in ('owner', 'admin', 'employee')),
  created_at       timestamptz not null default now(),

  -- a person can only have one badge per company
  unique (organization_id, user_id)
);


-- ---------------------------------------------------------------------
-- 3. Give every existing user a badge at Nextudio.
--    Roles are copied from app_users; the two partners become owners
--    (Mohamad Ramadan = mo@nextudio.co, Mohamad Omar = omar@nextudio.co).
-- ---------------------------------------------------------------------
insert into organization_members (organization_id, user_id, role)
select o.id,
       u.id,
       case
         when lower(u.email) in ('mo@nextudio.co', 'omar@nextudio.co') then 'owner'
         else u.role
       end
from app_users u
cross join organizations o
where o.name = 'Nextudio';


-- ---------------------------------------------------------------------
-- 4. Link each staff record to its owner's badge.
--    Today this link lives in app_users.employee_id; it is copied here.
--    Nullable: a staff record without a login is still allowed.
-- ---------------------------------------------------------------------
alter table employees
  add column organization_member_id bigint unique
  references organization_members(id) on delete restrict;

update employees e
set organization_member_id = m.id
from organization_members m
join app_users u on u.id = m.user_id
where u.employee_id = e.id;
